// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qHOgIakCL63kDh0N1b3hfiN5lHcquvA',
    appId: '1:487195058314:web:6e91de286567bdae584d73',
    messagingSenderId: '487195058314',
    projectId: 'toothhero-4102d',
    authDomain: 'toothhero-4102d.firebaseapp.com',
    storageBucket: 'toothhero-4102d.appspot.com',
    measurementId: 'G-8ZF4QZ61CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiUUfaPge_InSPJQfYGb6r9BKts3ajjA',
    appId: '1:487195058314:android:195c6a0b6999d648584d73',
    messagingSenderId: '487195058314',
    projectId: 'toothhero-4102d',
    storageBucket: 'toothhero-4102d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKoVP5xQ402MTQML7Ue8W5XXRJIBg3iA',
    appId: '1:487195058314:ios:108195563a61ba9b584d73',
    messagingSenderId: '487195058314',
    projectId: 'toothhero-4102d',
    storageBucket: 'toothhero-4102d.appspot.com',
    iosClientId: '487195058314-h372ddgeasd1rq0rfh0qonoj728ip0uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictureflutter',
  );
}
