// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfKGUab8aHpWPY8lx8XvNMKdVCibBnIA',
    appId: '1:1098231761617:web:2a5798b609afbf8dd513f0',
    messagingSenderId: '1098231761617',
    projectId: 'functionsteste-96ae0',
    authDomain: 'functionsteste-96ae0.firebaseapp.com',
    storageBucket: 'functionsteste-96ae0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PMkvzlee4r0sXJKqAyaAX94HwFqGwpY',
    appId: '1:1098231761617:android:c7d17e2dfa98c24fd513f0',
    messagingSenderId: '1098231761617',
    projectId: 'functionsteste-96ae0',
    storageBucket: 'functionsteste-96ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaOiYXZidSMBzVjGA7skinLGOKGl0kZA',
    appId: '1:1098231761617:ios:c970d7356edee1e2d513f0',
    messagingSenderId: '1098231761617',
    projectId: 'functionsteste-96ae0',
    storageBucket: 'functionsteste-96ae0.appspot.com',
    iosClientId: '1098231761617-4pqvti0habbcmqatgdg897tb6mau2r3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictureflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaOiYXZidSMBzVjGA7skinLGOKGl0kZA',
    appId: '1:1098231761617:ios:c970d7356edee1e2d513f0',
    messagingSenderId: '1098231761617',
    projectId: 'functionsteste-96ae0',
    storageBucket: 'functionsteste-96ae0.appspot.com',
    iosClientId: '1098231761617-4pqvti0habbcmqatgdg897tb6mau2r3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictureflutter',
  );
}
